trigger: none

pr: none

resources:
  pipelines:
  - pipeline: ciartifacts
    source: anvil-data-infrastructure-ci-artifacts
    trigger: 
      branches:
      - main
  repositories:
  - repository: mdwdataops_adfpublish
    type: github
    endpoint: anvil-data-infrastructure-github
    name: devlace/mdw-dataops-clone
    ref: adf_publish

# The deployment script sets this as a Pipeline Variable, but you may choose to set it here in the definition
#
# variables:
#   devAdfName: <DEV DATAFACTORY NAME>

stages:
- stage: deploy_to_dev
  displayName: 'Deploy to DEV'  # In DEV, excludes publishing to ADF as this is a manual publish step
  variables:
  - group: anvil-data-infrastructure-release-dev
  - group: anvil-data-infrastructure-secrets-dev
  jobs:
  - template: templates/jobs/deploy-databricks-job.yml
    parameters:
      environmentName: 'DEV'
  - template: templates/jobs/deploy-azuresqldb-job.yml
    parameters:
      environmentName: 'DEV'
      serviceConnection: 'anvil-data-infrastructure-serviceconnection-dev'

- stage: deploy_to_stg
  displayName: 'Deploy to Stage'
  variables:
  - group: anvil-data-infrastructure-release-stg
  - group: anvil-data-infrastructure-secrets-stg
  jobs: 
  - template: templates/jobs/deploy-databricks-job.yml
    parameters:
      environmentName: 'STG'
  - template: templates/jobs/deploy-azuresqldb-job.yml
    parameters:
      environmentName: 'STG'
      serviceConnection: 'anvil-data-infrastructure-serviceconnection-stg'
  - template: templates/jobs/deploy-adf-job.yml
    parameters:
      environmentName: 'STG'
      serviceConnection: 'anvil-data-infrastructure-serviceconnection-stg'
  # Integration tests
  - template: templates/jobs/integration-tests-job.yml

- stage: deploy_to_prod
  displayName: 'Deploy to Prod'
  variables:
  - group: anvil-data-infrastructure-release-prod
  - group: anvil-data-infrastructure-secrets-prod
  jobs: 
  - template: templates/jobs/deploy-databricks-job.yml
    parameters:
      environmentName: 'PROD'
  - template: templates/jobs/deploy-azuresqldb-job.yml
    parameters:
      environmentName: 'PROD'
      serviceConnection: 'anvil-data-infrastructure-serviceconnection-prod'
  - template: templates/jobs/deploy-adf-job.yml
    parameters:
      environmentName: 'PROD'
      serviceConnection: 'anvil-data-infrastructure-serviceconnection-prod'
